version: '3.7'

services:
  nginx:
    container_name: nginx
    environment:
      HTML_PATH: $HTML_PATH
    image: cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG
    networks:
      nginx_net:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
  backend-node:
    container_name: backend
    image: cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG
    volumes:
      - /tmp/data:/tmp/data
    networks:
      nginx_net:
    build:
      dockerfile: Dockerfile.backend

networks:
  nginx_net:
    name: nginx_net
