FROM nginx
COPY ./nginx.conf.template /nginx.conf.template
ADD https://raw.githubusercontent.com/certbot/certbot/refs/heads/main/certbot/certbot/ssl-dhparams.pem /etc/certbot/ssl-dhparams.pem
CMD ["/bin/sh" , "-c" , "envsubst < /nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
