on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install
        run: yarn

  linters:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install
        run: yarn
      - name: eslint
        run: yarn eslint
      - name: stylelint
        run: yarn stylelint
      - name: prettier
        run: yarn prettier

  unit:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install
        run: yarn
      - name: jest
        run: yarn jest

  integration:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: playwright
        run: yarn playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: packages/client/dist
          
