on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - uses: actions/checkout@v4
      - name: install
        run: yarn

  linters:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - uses: actions/checkout@v4
      - name: install
        run: yarn
      - name: eslint
        run: yarn eslint
      - name: stylelint
        run: yarn stylelint
      - name: prettier
        run: yarn prettier

  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - uses: actions/checkout@v4
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: packages/client/dist
          
